import { browser } from 'wxt/browser'

export const MSG = {
    GET_STATE: 'GET_STATE',
    MEDIA_STATE_CHANGED: 'MEDIA_STATE_CHANGED',

    GET_SUMMARY: 'GET_SUMMARY',
    SUMMARY_CHANGED: 'SUMMARY_CHANGED',

    GET_PRIMARY: 'GET_PRIMARY',
    PRIMARY_CHANGED: 'PRIMARY_CHANGED',

    PRIMARY_AUDIBLE_CHANGED: 'PRIMARY_AUDIBLE_CHANGED',

    GET_TAB_OVERRIDE: 'GET_TAB_OVERRIDE',
    SET_TAB_OVERRIDE: 'SET_TAB_OVERRIDE',
    TAB_OVERRIDE_CHANGED: 'TAB_OVERRIDE_CHANGED',

    REQUEST_CAPTURE: 'REQUEST_CAPTURE',
    CAPTURE_STREAM: 'CAPTURE_STREAM',
    CAPTURE_READY: 'CAPTURE_READY',
    CAPTURE_ENDED: 'CAPTURE_ENDED',
    GET_CAPTURE_STATE: 'GET_CAPTURE_STATE',
    CAPTURE_STATE_CHANGED: 'CAPTURE_STATE_CHANGED',
    SET_CAPTURED_VOLUME: 'SET_CAPTURED_VOLUME',
    STOP_CAPTURE: 'STOP_CAPTURE',

    GET_CAPTURED_TABS: 'GET_CAPTURED_TABS',

    SHOW_TOAST: 'SHOW_TOAST',
    GO_TO_TAB: 'GO_TO_TAB',
}

export function sendMessage(type, payload) {
    return browser.runtime.sendMessage({ type, payload })
}

export function sendTabMessage(tabId, type, payload) {
    return browser.tabs.sendMessage(tabId, { type, payload })
}
